# Usa una imagen de Node.js oficial
FROM node:20.11.0

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos de configuración del proyecto
COPY package.json ./
# package-lock.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto por defecto de Vite (5173)
EXPOSE 5173

# Comando para iniciar el servidor
CMD ["npm", "run", "dev"]