# Usa una imagen de Node.js oficial
FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del proyecto React
COPY . .

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar React
CMD ["npm", "start"]
