services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: sensor_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: sensor_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
